### ISSUE TITLE
Small mistake in bias calculation

### ISSUE THREAD

**Issue by hollance** [alankrantas/sefr_multiclass_classifier#1]
Hey, in the Python code (sefr.py) the bias calculation does the following:

```
bias = -(neg_labels.size * pos_score_avg + # calculate weighted average of bias
         pos_indices.size * neg_score_avg) / (neg_labels.size + pos_indices.size)
```

However, I think you meant to do:

```
bias = -(neg_indices.size * pos_score_avg + # calculate weighted average of bias
         pos_indices.size * neg_score_avg) / (neg_indices.size + pos_indices.size)
```

Instead of `neg_labels`, use `neg_indices`. The reason is that `neg_labels.size` is the length of the entire dataset but `neg_indices.size` is the number of negative examples.

**Comment by alankrantas** [comment]
Yes, you are right. Fixed. 👍
